# Single neuron

In [1]:
import numpy as np

In [2]:
X = np.array([
    [1, 2, 3],
    [4, 5, 6],
], dtype=float)

Y = np.array([
    [14],
    [32]
],dtype=float)

In [3]:
print(X)
print("---")
print(Y)

[[1. 2. 3.]
 [4. 5. 6.]]
---
[[14.]
 [32.]]


In [4]:
W = np.array([
    [1],
    [2],
    [3]
], dtype=float)

In [13]:
out = np.dot(X, W)

In [14]:
print(out)

[[14.]
 [32.]]
