# Attempting to build a neural network from scratch using NumPy

The goal is to build a simple Feed Forward Neural Network that can perform image classification on the MNIST dataset and see if it also works on the Fashion MNIST dataset, but only using NumPy (and maybe some visualizations for my own sake).

Idea from Green Code on YouTube

## Import libraries... well... just NumPy

In [1]:
import numpy as np

## Details

A neural network will have:
<ul>
    <li>Inputs</li>
    <li>Multiple neurons</li>
    <li>Connections between neurons</li>
    <li>Outputs</li>
</ul>

Since I will be focusing only on a basic Feed Forward Neural Network, I can think of a single neuron as:

![title](../assets/single_neuron.png)

Mathematically, this involves:
<ul>
    <li>Weighted sum</li>
    <li>Non-linear function, or activation</li>
</ul>

## Input

Let us consider a dataset of images.
<ul>
    <li>100 images</li>
    <li>Each image is 32x32 pixels with 1 channel</li>
</ul>

Considering that we flatten each pixel in an image to a linear array, we get an array of 32x32 = 1024 values.

Therefore, there will be 100 individual inputs of 1024 elements each.

To generalize this, if we take the number of samples in the dataset to be N and the number of features or elements in each sample to be M, the overall input array will be an NxM matrix where each column is a flattened representation of one image in the dataset.

In [2]:
# Faux input description
NUM_SAMPLES = 100
WIDTH = 32
HEIGHT = 32
M = WIDTH * HEIGHT

In [3]:
# Faux input
X = np.random.randn(NUM_SAMPLES,M)
print("Input")
print(X)

Input
[[ 0.70828555 -1.14134981  0.40991814 ... -0.42983519  0.54212707
   1.84919195]
 [-0.39127704  0.22836287  0.26580335 ... -0.41163135 -0.41355685
   0.12145822]
 [ 0.88739322  1.60616609  0.55957971 ... -0.54977064 -0.3869686
   0.76635303]
 ...
 [ 1.22599396 -2.27432461  0.86880996 ...  1.57627431 -1.214449
  -0.32336174]
 [ 1.65064186 -0.2983863   0.54441723 ...  0.76436665 -0.68017548
  -0.75038653]
 [-1.14860834  0.25911003 -0.21023958 ...  1.08614286 -0.5058246
  -0.2569    ]]


## Outputs

Let us assume that the 100 images are labeled into 10 classes. This becomes 

## Weights

In [4]:
W = 

SyntaxError: invalid syntax (702581706.py, line 1)

In [5]:
W = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
x = np.array([[1], [2], [3]], dtype=float)
dot = np.dot(W, x)
print(W)
print(x)
print(dot)
print(dot.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
[[1.]
 [2.]
 [3.]]
[[14.]
 [32.]]
(2, 1)
